Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`.

In [188]:
# Import libraries
import numpy as np
import pandas as pd

# Set up overall conditions
np.random.seed(123)
n_trials = 100_000

1. How likely is it that you roll doubles when rolling two dice?

In [102]:
# set up individual variables for our test
outcomes = list(range(1,7))
n_dice = 2

In [104]:
rolls = np.random.choice(outcomes,(n_trials,n_dice))
rolls[:10]

array([[6, 3],
       [5, 3],
       [2, 4],
       [3, 4],
       [2, 2],
       [1, 2],
       [2, 1],
       [1, 2],
       [4, 6],
       [5, 1]])

In [106]:
# Determine if roll 1 is also roll 2
(rolls[:,0] == rolls[:,1]).sum() / len(rolls)

0.16497

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [110]:
# Adjust outcomes and set number of coins
outcomes = ['H','T']
n_coins = 8

# Create number of trials
flips = np.random.choice(outcomes,(n_trials,n_coins))
flips[:10]

array([['T', 'T', 'H', 'H', 'H', 'T', 'T', 'H'],
       ['H', 'H', 'T', 'T', 'H', 'H', 'H', 'H'],
       ['H', 'H', 'T', 'T', 'T', 'H', 'H', 'H'],
       ['H', 'H', 'T', 'H', 'T', 'H', 'H', 'T'],
       ['H', 'H', 'H', 'H', 'T', 'H', 'H', 'H'],
       ['H', 'H', 'H', 'H', 'T', 'T', 'H', 'T'],
       ['H', 'T', 'T', 'T', 'T', 'H', 'H', 'T'],
       ['H', 'T', 'T', 'H', 'H', 'H', 'T', 'H'],
       ['H', 'H', 'H', 'T', 'H', 'H', 'H', 'T'],
       ['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T']], dtype='<U1')

In [120]:
# Determine probability of exactly 3 heads

# First turn each flip into a boolean to check for heads, then get the row summary
# Then if the row summary is equal to 3, sum that new boolean and divide by length of flips
# to get final probability
((flips == 'H').sum(axis=1) == 3).sum() / len(flips)

0.22152

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [127]:
# 3 web dev to 1 data science = 1/4th classes is a DS class
# So it'll be something along the lines of 1/4 classes times 1/4
# So our answer should look something like 1/16
1/16

0.0625

In [133]:
outcomes = ['DS','WD','WD','WD']
n_boards = 2

billboards = np.random.choice(outcomes,(n_trials,n_boards))
billboards[:10]

array([['WD', 'WD'],
       ['DS', 'DS'],
       ['WD', 'DS'],
       ['DS', 'DS'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD']], dtype='<U2')

In [156]:
# Create test condition against 'DS' for Data Science
# Sum across rows
# If the sum total equals 2, then 'DS' is on both billboards (turn that into a boolean)
# Then get the sum of booleans divided by length of billboards
((billboards == 'DS').sum(axis=1) == 2).sum() / len(billboards)

0.06212

In [158]:
# Try this with mean
((billboards == 'DS').sum(axis=1) == 2).mean()

0.06212

In [ ]:
# And 0.06212 is approximately correct to the odds we expect to see

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the `np.random.normal`) *You'll need to make a judgement call on how to handle some of your values*

In [192]:
# Get an idea of using np.random.normal, and once familiarized, set that to a variable
daily_poptarts = np.random.normal(loc=3.0,scale=1.5,size=(n_trials,5))
daily_poptarts[:10]

array([[ 3.07773146,  0.65626657,  1.86210717,  3.24590125,  4.18061113],
       [ 0.56605668,  1.74638906,  6.79136252,  3.1698458 ,  0.13291953],
       [ 3.35087413,  0.25321737,  1.72008744,  2.29887107,  4.31741925],
       [ 6.96537427,  3.53455376,  1.23820404,  2.99731588,  3.30946528],
       [ 3.91808216,  1.93849376,  1.57687312,  4.07433203,  3.35246141],
       [ 4.59303919,  1.74392394,  3.18490786,  4.54681148,  2.31749471],
       [ 2.40841791,  2.67111966,  3.03199666,  3.13452285,  2.87715141],
       [ 4.30817539,  2.80135622,  1.06647321,  2.93235346,  3.32213679],
       [ 5.42112318,  3.61702991,  5.77081748,  4.20070418, -1.14084306],
       [ 5.26588364,  2.64550824,  5.85830903,  4.21287266,  3.37364689]])

In [196]:
# Making some assumptions here, but summing each row then subtracting that sum
# from 17 (for initial starting value) should yield approximately how many packages are left
# on Friday afternoon/evening
end_consumption = 17 - daily_poptarts.sum(axis=1)
end_consumption[:10]

array([ 3.97738241,  4.59342642,  5.05953073, -1.04491323,  2.13975752,
        0.61382281,  2.87679152,  2.56950492, -0.86883169, -4.35622046])

In [202]:
# Can't buy less than 1 package, so compare each value against 1
# Then get the mean of those booleans
(end_consumption > 1).mean()

0.61677

In [277]:
# Try altogether now
daily_poptarts = np.random.normal(loc=3.0,scale=1.5,size=(n_trials,5))
end_consumption = 17 - daily_poptarts.sum(axis=1)
(end_consumption > 1).mean().round(2)

# End value tends to be about 0.62, rounded

0.62

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.

In [312]:
# Establish male height and std
m_ht = 178
m_sd = 8

# make the array of male heights
m_heights = np.random.normal(m_ht,m_sd,(n_trials))
m_heights[:10]

array([179.13153748, 162.28398036, 175.17029114, 177.83020192,
       185.41059715, 173.63605388, 180.43760246, 171.37571194,
       170.77512469, 180.26629534])

- Women have a mean of 170, sd = 6cm.

In [314]:
# Establish female height and std
f_ht = 170
f_sd = 6

# make the array of female heights
f_heights = np.random.normal(f_ht,f_sd,(n_trials))
f_heights[:10]

array([177.33026046, 181.44317169, 174.23524626, 169.88532839,
       171.4964751 , 162.03689301, 165.90765545, 162.17987297,
       168.38113977, 178.04107534])

- Since you have means and standard deviations, you can use `np.random.normal` to generate observations.

In [354]:
# Establish a DataFrame to hold randomized comparisons
# Dataframe not necessary, but it makes things easier

heights = pd.DataFrame(
    {
        'male_height':np.random.choice(m_heights,(n_trials)),
        'female_height':np.random.choice(f_heights,(n_trials))
    }
)

heights.describe().round()

male_height  female_height
count     100000.0       100000.0
mean         178.0          170.0
std            8.0            6.0
min          145.0          141.0
25%          173.0          166.0
50%          178.0          170.0
75%          183.0          174.0
max          214.0          195.0

- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [349]:
# Simple boolean comparison and voila, we have our probability!
(heights.female_height > heights.male_height).mean()

0.20929

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [ ]:
download_fail = 1/250

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?